export const mockProducts = [
  {
    id: "1",
    name: "Gentle Foaming Cleanser",
    brand: "CeraVe",
    category: "cleanser",
    price: "$15",
    priceRange: "budget",
    description: "Gentle, non-irritating cleanser that removes dirt and oil while maintaining skin's natural barrier",
    skinTypes: ["oily", "combination", "normal"],
    concerns: ["acne", "blackheads"],
    image: "/cleanser-bottle.jpg",
  },
  {
    id: "2",
    name: "Hydrating Facial Cleanser",
    brand: "CeraVe",
    category: "cleanser",
    price: "$16",
    priceRange: "budget",
    description: "Hydrating cleanser for dry to normal skin with hyaluronic acid and ceramides",
    skinTypes: ["dry", "normal", "sensitive"],
    concerns: ["redness"],
    image: "/hydrating-cleanser.jpg",
  },
  {
    id: "3",
    name: "Salicylic Acid Cleanser",
    brand: "The Ordinary",
    category: "cleanser",
    price: "$12",
    priceRange: "budget",
    description: "Exfoliating cleanser with 2% salicylic acid to target acne and blackheads",
    skinTypes: ["oily", "combination"],
    concerns: ["acne", "blackheads", "large-pores"],
    image: "/salicylic-acid-cleanser.jpg",
  },
  {
    id: "4",
    name: "Niacinamide Serum",
    brand: "The Ordinary",
    category: "serum",
    price: "$10",
    priceRange: "budget",
    description: "10% niacinamide + 1% zinc to reduce blemishes and congestion",
    skinTypes: ["oily", "combination", "normal"],
    concerns: ["acne", "redness", "large-pores"],
    image: "/niacinamide-serum.jpg",
  },
  {
    id: "5",
    name: "Hyaluronic Acid Serum",
    brand: "The Ordinary",
    category: "serum",
    price: "$9",
    priceRange: "budget",
    description: "Multi-molecular hyaluronic acid complex for deep hydration",
    skinTypes: ["dry", "normal", "combination"],
    concerns: ["uneven-texture"],
    image: "/hyaluronic-acid-serum.jpg",
  },
  {
    id: "6",
    name: "Vitamin C Serum",
    brand: "La Roche-Posay",
    category: "serum",
    price: "$40",
    priceRange: "moderate",
    description: "Pure vitamin C serum to brighten and even skin tone",
    skinTypes: ["normal", "combination", "oily"],
    concerns: ["fine-lines", "scarring"],
    image: "/vitamin-c-serum.png",
  },
  {
    id: "7",
    name: "Benzoyl Peroxide Treatment",
    brand: "Paula's Choice",
    category: "treatment",
    price: "$25",
    priceRange: "moderate",
    description: "2.5% benzoyl peroxide gel to treat and prevent acne",
    skinTypes: ["oily", "combination"],
    concerns: ["acne", "pih"],
    image: "/benzoyl-peroxide-treatment.jpg",
  },
  {
    id: "8",
    name: "Retinol Serum",
    brand: "Paula's Choice",
    category: "treatment",
    price: "$58",
    priceRange: "premium",
    description: "1% retinol treatment to improve texture and reduce acne",
    skinTypes: ["normal", "combination", "oily"],
    concerns: ["acne", "scarring", "uneven-texture"],
    image: "/retinol-serum.png",
  },
  {
    id: "9",
    name: "Lightweight Gel Moisturizer",
    brand: "Neutrogena",
    category: "moisturizer",
    price: "$18",
    priceRange: "budget",
    description: "Oil-free gel moisturizer for oily and acne-prone skin",
    skinTypes: ["oily", "combination"],
    concerns: ["acne"],
    image: "/gel-moisturizer.png",
  },
  {
    id: "10",
    name: "Rich Cream Moisturizer",
    brand: "CeraVe",
    category: "moisturizer",
    price: "$19",
    priceRange: "budget",
    description: "Rich, hydrating cream with ceramides for dry skin",
    skinTypes: ["dry", "sensitive"],
    concerns: ["redness"],
    image: "/rich-cream-moisturizer.jpg",
  },
  {
    id: "11",
    name: "SPF 50 Sunscreen",
    brand: "La Roche-Posay",
    category: "sunscreen",
    price: "$35",
    priceRange: "moderate",
    description: "Broad spectrum SPF 50 sunscreen for daily protection",
    skinTypes: ["all"],
    concerns: ["fine-lines", "scarring"],
    image: "/sunscreen-spf-50.jpg",
  },
  {
    id: "12",
    name: "Exfoliating Toner",
    brand: "Paula's Choice",
    category: "toner",
    price: "$32",
    priceRange: "moderate",
    description: "2% BHA liquid exfoliant to unclog pores and smooth skin",
    skinTypes: ["oily", "combination"],
    concerns: ["acne", "blackheads", "large-pores"],
    image: "/exfoliating-toner.jpg",
  },
]

export const mockVideos = [
  {
    id: "1",
    title: "Complete Morning Skincare Routine for Acne-Prone Skin",
    channel: "Hyram",
    duration: 12,
    topic: "routine",
    thumbnail: "/morning-skincare-routine.png",
    views: "2.5M",
  },
  {
    id: "2",
    title: "Evening Skincare Routine for Clear Skin",
    channel: "James Welsh",
    duration: 15,
    topic: "routine",
    thumbnail: "/evening-skincare-routine.jpg",
    views: "1.8M",
  },
  {
    id: "3",
    title: "CeraVe Cleanser Review - Is It Worth The Hype?",
    channel: "Dr. Dray",
    duration: 8,
    topic: "review",
    thumbnail: "/cerave-cleanser-review.jpg",
    views: "950K",
  },
  {
    id: "4",
    title: "How to Use Retinol for Beginners",
    channel: "Dr. Shereene Idriss",
    duration: 18,
    topic: "tutorial",
    thumbnail: "/retinol-tutorial.jpg",
    views: "1.2M",
  },
  {
    id: "5",
    title: "Understanding Acne Types and Treatments",
    channel: "Doctorly",
    duration: 22,
    topic: "education",
    thumbnail: "/acne-types-education.jpg",
    views: "3.1M",
  },
  {
    id: "6",
    title: "The Ordinary Niacinamide Review",
    channel: "Hyram",
    duration: 10,
    topic: "review",
    thumbnail: "/niacinamide-review.jpg",
    views: "1.5M",
  },
  {
    id: "7",
    title: "How to Layer Skincare Products Correctly",
    channel: "James Welsh",
    duration: 14,
    topic: "tutorial",
    thumbnail: "/layering-skincare-tutorial.jpg",
    views: "2.2M",
  },
  {
    id: "8",
    title: "Best Budget Skincare Products for Acne",
    channel: "Dr. Dray",
    duration: 16,
    topic: "review",
    thumbnail: "/placeholder.svg?height=200&width=300",
    views: "1.9M",
  },
  {
    id: "9",
    title: "Skincare Ingredients You Should Know",
    channel: "Doctorly",
    duration: 25,
    topic: "education",
    thumbnail: "/placeholder.svg?height=200&width=300",
    views: "2.8M",
  },
  {
    id: "10",
    title: "Double Cleansing Method Tutorial",
    channel: "Dr. Shereene Idriss",
    duration: 9,
    topic: "tutorial",
    thumbnail: "/placeholder.svg?height=200&width=300",
    views: "1.1M",
  },
  {
    id: "11",
    title: "My Acne Journey and What Worked",
    channel: "Hyram",
    duration: 20,
    topic: "education",
    thumbnail: "/placeholder.svg?height=200&width=300",
    views: "4.2M",
  },
  {
    id: "12",
    title: "Sunscreen 101: Everything You Need to Know",
    channel: "Dr. Dray",
    duration: 17,
    topic: "education",
    thumbnail: "/placeholder.svg?height=200&width=300",
    views: "2.6M",
  },
]
